my:
  server:
    port: 8081
    host: localhost
spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/easybuy?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    name: easybuy
    password: root
    data-username: root
    data-password: root
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#spring.view
#  freemarker:
#    check-template-location: false
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
